//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IZOKALE_WEBSERVICE.WCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.ISvc")]
    public interface ISvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/AppendDataObject", ReplyAction="http://tempuri.org/ISvc/AppendDataObjectResponse")]
        IZOKALE_WEBSERVICE.WCFService.AppendDataObjectResponse AppendDataObject(IZOKALE_WEBSERVICE.WCFService.AppendDataObjectRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/AppendDataObject", ReplyAction="http://tempuri.org/ISvc/AppendDataObjectResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.AppendDataObjectResponse> AppendDataObjectAsync(IZOKALE_WEBSERVICE.WCFService.AppendDataObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ReadDataObject", ReplyAction="http://tempuri.org/ISvc/ReadDataObjectResponse")]
        IZOKALE_WEBSERVICE.WCFService.ReadDataObjectResponse ReadDataObject(IZOKALE_WEBSERVICE.WCFService.ReadDataObjectRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ReadDataObject", ReplyAction="http://tempuri.org/ISvc/ReadDataObjectResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.ReadDataObjectResponse> ReadDataObjectAsync(IZOKALE_WEBSERVICE.WCFService.ReadDataObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ReadDataObjectXML", ReplyAction="http://tempuri.org/ISvc/ReadDataObjectXMLResponse")]
        IZOKALE_WEBSERVICE.WCFService.ReadDataObjectXMLResponse ReadDataObjectXML(IZOKALE_WEBSERVICE.WCFService.ReadDataObjectXMLRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ReadDataObjectXML", ReplyAction="http://tempuri.org/ISvc/ReadDataObjectXMLResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.ReadDataObjectXMLResponse> ReadDataObjectXMLAsync(IZOKALE_WEBSERVICE.WCFService.ReadDataObjectXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/DeleteDataObject", ReplyAction="http://tempuri.org/ISvc/DeleteDataObjectResponse")]
        IZOKALE_WEBSERVICE.WCFService.DeleteDataObjectResponse DeleteDataObject(IZOKALE_WEBSERVICE.WCFService.DeleteDataObjectRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/DeleteDataObject", ReplyAction="http://tempuri.org/ISvc/DeleteDataObjectResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.DeleteDataObjectResponse> DeleteDataObjectAsync(IZOKALE_WEBSERVICE.WCFService.DeleteDataObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/CalculateDataObject", ReplyAction="http://tempuri.org/ISvc/CalculateDataObjectResponse")]
        IZOKALE_WEBSERVICE.WCFService.CalculateDataObjectResponse CalculateDataObject(IZOKALE_WEBSERVICE.WCFService.CalculateDataObjectRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/CalculateDataObject", ReplyAction="http://tempuri.org/ISvc/CalculateDataObjectResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.CalculateDataObjectResponse> CalculateDataObjectAsync(IZOKALE_WEBSERVICE.WCFService.CalculateDataObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ExecQuery", ReplyAction="http://tempuri.org/ISvc/ExecQueryResponse")]
        IZOKALE_WEBSERVICE.WCFService.ExecQueryResponse ExecQuery(IZOKALE_WEBSERVICE.WCFService.ExecQueryRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ExecQuery", ReplyAction="http://tempuri.org/ISvc/ExecQueryResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.ExecQueryResponse> ExecQueryAsync(IZOKALE_WEBSERVICE.WCFService.ExecQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/DirectQuery", ReplyAction="http://tempuri.org/ISvc/DirectQueryResponse")]
        IZOKALE_WEBSERVICE.WCFService.DirectQueryResponse DirectQuery(IZOKALE_WEBSERVICE.WCFService.DirectQueryRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/DirectQuery", ReplyAction="http://tempuri.org/ISvc/DirectQueryResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.DirectQueryResponse> DirectQueryAsync(IZOKALE_WEBSERVICE.WCFService.DirectQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getValue", ReplyAction="http://tempuri.org/ISvc/getValueResponse")]
        IZOKALE_WEBSERVICE.WCFService.getValueResponse getValue(IZOKALE_WEBSERVICE.WCFService.getValueRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getValue", ReplyAction="http://tempuri.org/ISvc/getValueResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.getValueResponse> getValueAsync(IZOKALE_WEBSERVICE.WCFService.getValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getTableName", ReplyAction="http://tempuri.org/ISvc/getTableNameResponse")]
        string getTableName(int TableNr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getTableName", ReplyAction="http://tempuri.org/ISvc/getTableNameResponse")]
        System.Threading.Tasks.Task<string> getTableNameAsync(int TableNr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/printDoc", ReplyAction="http://tempuri.org/ISvc/printDocResponse")]
        void printDoc(short doctype, int docRef, string termCode, string designTitle, string printerCode, short printCnt, string securityCode, string LbsLoadPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/printDoc", ReplyAction="http://tempuri.org/ISvc/printDocResponse")]
        System.Threading.Tasks.Task printDocAsync(short doctype, int docRef, string termCode, string designTitle, string printerCode, short printCnt, string securityCode, string LbsLoadPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getInfo", ReplyAction="http://tempuri.org/ISvc/getInfoResponse")]
        IZOKALE_WEBSERVICE.WCFService.getInfoResponse getInfo(IZOKALE_WEBSERVICE.WCFService.getInfoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getInfo", ReplyAction="http://tempuri.org/ISvc/getInfoResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.getInfoResponse> getInfoAsync(IZOKALE_WEBSERVICE.WCFService.getInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getStockPriceList", ReplyAction="http://tempuri.org/ISvc/getStockPriceListResponse")]
        IZOKALE_WEBSERVICE.WCFService.getStockPriceListResponse getStockPriceList(IZOKALE_WEBSERVICE.WCFService.getStockPriceListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getStockPriceList", ReplyAction="http://tempuri.org/ISvc/getStockPriceListResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.getStockPriceListResponse> getStockPriceListAsync(IZOKALE_WEBSERVICE.WCFService.getStockPriceListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/UsableCampaignCards", ReplyAction="http://tempuri.org/ISvc/UsableCampaignCardsResponse")]
        IZOKALE_WEBSERVICE.WCFService.UsableCampaignCardsResponse UsableCampaignCards(IZOKALE_WEBSERVICE.WCFService.UsableCampaignCardsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/UsableCampaignCards", ReplyAction="http://tempuri.org/ISvc/UsableCampaignCardsResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.UsableCampaignCardsResponse> UsableCampaignCardsAsync(IZOKALE_WEBSERVICE.WCFService.UsableCampaignCardsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/SendRecvEInvoiceDocuments", ReplyAction="http://tempuri.org/ISvc/SendRecvEInvoiceDocumentsResponse")]
        IZOKALE_WEBSERVICE.WCFService.SendRecvEInvoiceDocumentsResponse SendRecvEInvoiceDocuments(IZOKALE_WEBSERVICE.WCFService.SendRecvEInvoiceDocumentsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/SendRecvEInvoiceDocuments", ReplyAction="http://tempuri.org/ISvc/SendRecvEInvoiceDocumentsResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.SendRecvEInvoiceDocumentsResponse> SendRecvEInvoiceDocumentsAsync(IZOKALE_WEBSERVICE.WCFService.SendRecvEInvoiceDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/SendEArchiveDocuments", ReplyAction="http://tempuri.org/ISvc/SendEArchiveDocumentsResponse")]
        IZOKALE_WEBSERVICE.WCFService.SendEArchiveDocumentsResponse SendEArchiveDocuments(IZOKALE_WEBSERVICE.WCFService.SendEArchiveDocumentsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/SendEArchiveDocuments", ReplyAction="http://tempuri.org/ISvc/SendEArchiveDocumentsResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.SendEArchiveDocumentsResponse> SendEArchiveDocumentsAsync(IZOKALE_WEBSERVICE.WCFService.SendEArchiveDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/SendRecvEDispatchDocuments", ReplyAction="http://tempuri.org/ISvc/SendRecvEDispatchDocumentsResponse")]
        IZOKALE_WEBSERVICE.WCFService.SendRecvEDispatchDocumentsResponse SendRecvEDispatchDocuments(IZOKALE_WEBSERVICE.WCFService.SendRecvEDispatchDocumentsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/SendRecvEDispatchDocuments", ReplyAction="http://tempuri.org/ISvc/SendRecvEDispatchDocumentsResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.SendRecvEDispatchDocumentsResponse> SendRecvEDispatchDocumentsAsync(IZOKALE_WEBSERVICE.WCFService.SendRecvEDispatchDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/SendESEVoucherDocuments", ReplyAction="http://tempuri.org/ISvc/SendESEVoucherDocumentsResponse")]
        IZOKALE_WEBSERVICE.WCFService.SendESEVoucherDocumentsResponse SendESEVoucherDocuments(IZOKALE_WEBSERVICE.WCFService.SendESEVoucherDocumentsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/SendESEVoucherDocuments", ReplyAction="http://tempuri.org/ISvc/SendESEVoucherDocumentsResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.SendESEVoucherDocumentsResponse> SendESEVoucherDocumentsAsync(IZOKALE_WEBSERVICE.WCFService.SendESEVoucherDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/SendESEPreceiptDocuments", ReplyAction="http://tempuri.org/ISvc/SendESEPreceiptDocumentsResponse")]
        IZOKALE_WEBSERVICE.WCFService.SendESEPreceiptDocumentsResponse SendESEPreceiptDocuments(IZOKALE_WEBSERVICE.WCFService.SendESEPreceiptDocumentsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/SendESEPreceiptDocuments", ReplyAction="http://tempuri.org/ISvc/SendESEPreceiptDocumentsResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.SendESEPreceiptDocumentsResponse> SendESEPreceiptDocumentsAsync(IZOKALE_WEBSERVICE.WCFService.SendESEPreceiptDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/GetEDocumentContent", ReplyAction="http://tempuri.org/ISvc/GetEDocumentContentResponse")]
        IZOKALE_WEBSERVICE.WCFService.GetEDocumentContentResponse GetEDocumentContent(IZOKALE_WEBSERVICE.WCFService.GetEDocumentContentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/GetEDocumentContent", ReplyAction="http://tempuri.org/ISvc/GetEDocumentContentResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.GetEDocumentContentResponse> GetEDocumentContentAsync(IZOKALE_WEBSERVICE.WCFService.GetEDocumentContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/UpdateEDocumentStatus", ReplyAction="http://tempuri.org/ISvc/UpdateEDocumentStatusResponse")]
        IZOKALE_WEBSERVICE.WCFService.UpdateEDocumentStatusResponse UpdateEDocumentStatus(IZOKALE_WEBSERVICE.WCFService.UpdateEDocumentStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/UpdateEDocumentStatus", ReplyAction="http://tempuri.org/ISvc/UpdateEDocumentStatusResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.UpdateEDocumentStatusResponse> UpdateEDocumentStatusAsync(IZOKALE_WEBSERVICE.WCFService.UpdateEDocumentStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/SaveEDocument", ReplyAction="http://tempuri.org/ISvc/SaveEDocumentResponse")]
        IZOKALE_WEBSERVICE.WCFService.SaveEDocumentResponse SaveEDocument(IZOKALE_WEBSERVICE.WCFService.SaveEDocumentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/SaveEDocument", ReplyAction="http://tempuri.org/ISvc/SaveEDocumentResponse")]
        System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.SaveEDocumentResponse> SaveEDocumentAsync(IZOKALE_WEBSERVICE.WCFService.SaveEDocumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AppendDataObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AppendDataObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public AppendDataObjectRequest() {
        }
        
        public AppendDataObjectRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AppendDataObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AppendDataObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public AppendDataObjectResponse() {
        }
        
        public AppendDataObjectResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status) {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadDataObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public ReadDataObjectRequest() {
        }
        
        public ReadDataObjectRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadDataObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public ReadDataObjectResponse() {
        }
        
        public ReadDataObjectResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status) {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataObjectXML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadDataObjectXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public ReadDataObjectXMLRequest() {
        }
        
        public ReadDataObjectXMLRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataObjectXMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadDataObjectXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public ReadDataObjectXMLResponse() {
        }
        
        public ReadDataObjectXMLResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status) {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDataObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDataObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string securityCode;
        
        public DeleteDataObjectRequest() {
        }
        
        public DeleteDataObjectRequest(int dataType, int dataReference, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDataObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDataObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte status;
        
        public DeleteDataObjectResponse() {
        }
        
        public DeleteDataObjectResponse(string errorString, byte status) {
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculateDataObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalculateDataObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public CalculateDataObjectRequest() {
        }
        
        public CalculateDataObjectRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculateDataObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalculateDataObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public CalculateDataObjectResponse() {
        }
        
        public CalculateDataObjectResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status) {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecQuery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sqlText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string orderByText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string securityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public object resultXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        public ExecQueryRequest() {
        }
        
        public ExecQueryRequest(string sqlText, string orderByText, string securityCode, object resultXML, string errorString, byte status, string LbsLoadPass) {
            this.sqlText = sqlText;
            this.orderByText = orderByText;
            this.securityCode = securityCode;
            this.resultXML = resultXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecQueryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object resultXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte status;
        
        public ExecQueryResponse() {
        }
        
        public ExecQueryResponse(object resultXML, string errorString, byte status) {
            this.resultXML = resultXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DirectQuery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DirectQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sqlText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string securityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LbsLoadPass;
        
        public DirectQueryRequest() {
        }
        
        public DirectQueryRequest(string sqlText, string securityCode, string errorString, byte status, string LbsLoadPass) {
            this.sqlText = sqlText;
            this.securityCode = securityCode;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DirectQueryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DirectQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte status;
        
        public DirectQueryResponse() {
        }
        
        public DirectQueryResponse(string errorString, byte status) {
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValue", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public short Flag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool isFlag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string securityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LbsLoadPass;
        
        public getValueRequest() {
        }
        
        public getValueRequest(short Flag, int Value, bool isFlag, string securityCode, string LbsLoadPass) {
            this.Flag = Flag;
            this.Value = Value;
            this.isFlag = isFlag;
            this.securityCode = securityCode;
            this.LbsLoadPass = LbsLoadPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Value;
        
        public getValueResponse() {
        }
        
        public getValueResponse(int Value) {
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object resultXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string securityCode;
        
        public getInfoRequest() {
        }
        
        public getInfoRequest(object resultXML, string securityCode) {
            this.resultXML = resultXML;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object resultXML;
        
        public getInfoResponse() {
        }
        
        public getInfoResponse(object resultXML) {
            this.resultXML = resultXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStockPriceList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getStockPriceListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string priceParamJson;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string priceListJson;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string securityCode;
        
        public getStockPriceListRequest() {
        }
        
        public getStockPriceListRequest(string priceParamJson, string priceListJson, string securityCode) {
            this.priceParamJson = priceParamJson;
            this.priceListJson = priceListJson;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStockPriceListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getStockPriceListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string priceListJson;
        
        public getStockPriceListResponse() {
        }
        
        public getStockPriceListResponse(string priceListJson) {
            this.priceListJson = priceListJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsableCampaignCards", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UsableCampaignCardsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public UsableCampaignCardsRequest() {
        }
        
        public UsableCampaignCardsRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsableCampaignCardsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UsableCampaignCardsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public UsableCampaignCardsResponse() {
        }
        
        public UsableCampaignCardsResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status) {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendRecvEInvoiceDocuments", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendRecvEInvoiceDocumentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int send;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int recv;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string refs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string securityCode;
        
        public SendRecvEInvoiceDocumentsRequest() {
        }
        
        public SendRecvEInvoiceDocumentsRequest(int send, int recv, string refs, string msg, string LbsLoadPass, string securityCode) {
            this.send = send;
            this.recv = recv;
            this.refs = refs;
            this.msg = msg;
            this.LbsLoadPass = LbsLoadPass;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendRecvEInvoiceDocumentsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendRecvEInvoiceDocumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msg;
        
        public SendRecvEInvoiceDocumentsResponse() {
        }
        
        public SendRecvEInvoiceDocumentsResponse(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEArchiveDocuments", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEArchiveDocumentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string refs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string securityCode;
        
        public SendEArchiveDocumentsRequest() {
        }
        
        public SendEArchiveDocumentsRequest(string refs, string msg, string LbsLoadPass, string securityCode) {
            this.refs = refs;
            this.msg = msg;
            this.LbsLoadPass = LbsLoadPass;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEArchiveDocumentsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendEArchiveDocumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msg;
        
        public SendEArchiveDocumentsResponse() {
        }
        
        public SendEArchiveDocumentsResponse(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendRecvEDispatchDocuments", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendRecvEDispatchDocumentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int send;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int recv;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dispatchRefs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string receiptRefs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string securityCode;
        
        public SendRecvEDispatchDocumentsRequest() {
        }
        
        public SendRecvEDispatchDocumentsRequest(int send, int recv, string dispatchRefs, string receiptRefs, string msg, string LbsLoadPass, string securityCode) {
            this.send = send;
            this.recv = recv;
            this.dispatchRefs = dispatchRefs;
            this.receiptRefs = receiptRefs;
            this.msg = msg;
            this.LbsLoadPass = LbsLoadPass;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendRecvEDispatchDocumentsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendRecvEDispatchDocumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msg;
        
        public SendRecvEDispatchDocumentsResponse() {
        }
        
        public SendRecvEDispatchDocumentsResponse(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendESEVoucherDocuments", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendESEVoucherDocumentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string clfRefs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cashRefs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string securityCode;
        
        public SendESEVoucherDocumentsRequest() {
        }
        
        public SendESEVoucherDocumentsRequest(string clfRefs, string cashRefs, string msg, string LbsLoadPass, string securityCode) {
            this.clfRefs = clfRefs;
            this.cashRefs = cashRefs;
            this.msg = msg;
            this.LbsLoadPass = LbsLoadPass;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendESEVoucherDocumentsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendESEVoucherDocumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msg;
        
        public SendESEVoucherDocumentsResponse() {
        }
        
        public SendESEVoucherDocumentsResponse(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendESEPreceiptDocuments", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendESEPreceiptDocumentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string refs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string securityCode;
        
        public SendESEPreceiptDocumentsRequest() {
        }
        
        public SendESEPreceiptDocumentsRequest(string refs, string msg, string LbsLoadPass, string securityCode) {
            this.refs = refs;
            this.msg = msg;
            this.LbsLoadPass = LbsLoadPass;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendESEPreceiptDocumentsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendESEPreceiptDocumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msg;
        
        public SendESEPreceiptDocumentsResponse() {
        }
        
        public SendESEPreceiptDocumentsResponse(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEDocumentContent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEDocumentContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string docTyp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string outFormat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string GUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string securityCode;
        
        public GetEDocumentContentRequest() {
        }
        
        public GetEDocumentContentRequest(string docTyp, string outFormat, string GUID, string msg, string LbsLoadPass, string securityCode) {
            this.docTyp = docTyp;
            this.outFormat = outFormat;
            this.GUID = GUID;
            this.msg = msg;
            this.LbsLoadPass = LbsLoadPass;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEDocumentContentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEDocumentContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msg;
        
        public GetEDocumentContentResponse() {
        }
        
        public GetEDocumentContentResponse(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateEDocumentStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateEDocumentStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string docTyp;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string refs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string securityCode;
        
        public UpdateEDocumentStatusRequest() {
        }
        
        public UpdateEDocumentStatusRequest(string docTyp, string refs, string msg, string LbsLoadPass, string securityCode) {
            this.docTyp = docTyp;
            this.refs = refs;
            this.msg = msg;
            this.LbsLoadPass = LbsLoadPass;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateEDocumentStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateEDocumentStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msg;
        
        public UpdateEDocumentStatusResponse() {
        }
        
        public UpdateEDocumentStatusResponse(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveEDocument", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveEDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int approvalRef;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string securityCode;
        
        public SaveEDocumentRequest() {
        }
        
        public SaveEDocumentRequest(int approvalRef, string msg, string LbsLoadPass, string securityCode) {
            this.approvalRef = approvalRef;
            this.msg = msg;
            this.LbsLoadPass = LbsLoadPass;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveEDocumentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveEDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msg;
        
        public SaveEDocumentResponse() {
        }
        
        public SaveEDocumentResponse(string msg) {
            this.msg = msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcChannel : IZOKALE_WEBSERVICE.WCFService.ISvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcClient : System.ServiceModel.ClientBase<IZOKALE_WEBSERVICE.WCFService.ISvc>, IZOKALE_WEBSERVICE.WCFService.ISvc {
        
        public SvcClient() {
        }
        
        public SvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.AppendDataObjectResponse IZOKALE_WEBSERVICE.WCFService.ISvc.AppendDataObject(IZOKALE_WEBSERVICE.WCFService.AppendDataObjectRequest request) {
            return base.Channel.AppendDataObject(request);
        }
        
        public void AppendDataObject(int dataType, ref int dataReference, ref string dataXML, ref string paramXML, ref string errorString, ref byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.AppendDataObjectRequest inValue = new IZOKALE_WEBSERVICE.WCFService.AppendDataObjectRequest();
            inValue.dataType = dataType;
            inValue.dataReference = dataReference;
            inValue.dataXML = dataXML;
            inValue.paramXML = paramXML;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.FirmNr = FirmNr;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.AppendDataObjectResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).AppendDataObject(inValue);
            dataReference = retVal.dataReference;
            dataXML = retVal.dataXML;
            paramXML = retVal.paramXML;
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.AppendDataObjectResponse> AppendDataObjectAsync(IZOKALE_WEBSERVICE.WCFService.AppendDataObjectRequest request) {
            return base.Channel.AppendDataObjectAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.ReadDataObjectResponse IZOKALE_WEBSERVICE.WCFService.ISvc.ReadDataObject(IZOKALE_WEBSERVICE.WCFService.ReadDataObjectRequest request) {
            return base.Channel.ReadDataObject(request);
        }
        
        public void ReadDataObject(int dataType, ref int dataReference, ref string dataXML, ref string paramXML, ref string errorString, ref byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.ReadDataObjectRequest inValue = new IZOKALE_WEBSERVICE.WCFService.ReadDataObjectRequest();
            inValue.dataType = dataType;
            inValue.dataReference = dataReference;
            inValue.dataXML = dataXML;
            inValue.paramXML = paramXML;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.FirmNr = FirmNr;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.ReadDataObjectResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).ReadDataObject(inValue);
            dataReference = retVal.dataReference;
            dataXML = retVal.dataXML;
            paramXML = retVal.paramXML;
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.ReadDataObjectResponse> ReadDataObjectAsync(IZOKALE_WEBSERVICE.WCFService.ReadDataObjectRequest request) {
            return base.Channel.ReadDataObjectAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.ReadDataObjectXMLResponse IZOKALE_WEBSERVICE.WCFService.ISvc.ReadDataObjectXML(IZOKALE_WEBSERVICE.WCFService.ReadDataObjectXMLRequest request) {
            return base.Channel.ReadDataObjectXML(request);
        }
        
        public void ReadDataObjectXML(int dataType, ref int dataReference, ref string dataXML, ref string paramXML, ref string errorString, ref byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.ReadDataObjectXMLRequest inValue = new IZOKALE_WEBSERVICE.WCFService.ReadDataObjectXMLRequest();
            inValue.dataType = dataType;
            inValue.dataReference = dataReference;
            inValue.dataXML = dataXML;
            inValue.paramXML = paramXML;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.FirmNr = FirmNr;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.ReadDataObjectXMLResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).ReadDataObjectXML(inValue);
            dataReference = retVal.dataReference;
            dataXML = retVal.dataXML;
            paramXML = retVal.paramXML;
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.ReadDataObjectXMLResponse> ReadDataObjectXMLAsync(IZOKALE_WEBSERVICE.WCFService.ReadDataObjectXMLRequest request) {
            return base.Channel.ReadDataObjectXMLAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.DeleteDataObjectResponse IZOKALE_WEBSERVICE.WCFService.ISvc.DeleteDataObject(IZOKALE_WEBSERVICE.WCFService.DeleteDataObjectRequest request) {
            return base.Channel.DeleteDataObject(request);
        }
        
        public void DeleteDataObject(int dataType, int dataReference, ref string errorString, ref byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.DeleteDataObjectRequest inValue = new IZOKALE_WEBSERVICE.WCFService.DeleteDataObjectRequest();
            inValue.dataType = dataType;
            inValue.dataReference = dataReference;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.FirmNr = FirmNr;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.DeleteDataObjectResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).DeleteDataObject(inValue);
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.DeleteDataObjectResponse> DeleteDataObjectAsync(IZOKALE_WEBSERVICE.WCFService.DeleteDataObjectRequest request) {
            return base.Channel.DeleteDataObjectAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.CalculateDataObjectResponse IZOKALE_WEBSERVICE.WCFService.ISvc.CalculateDataObject(IZOKALE_WEBSERVICE.WCFService.CalculateDataObjectRequest request) {
            return base.Channel.CalculateDataObject(request);
        }
        
        public void CalculateDataObject(int dataType, ref int dataReference, ref string dataXML, ref string paramXML, ref string errorString, ref byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.CalculateDataObjectRequest inValue = new IZOKALE_WEBSERVICE.WCFService.CalculateDataObjectRequest();
            inValue.dataType = dataType;
            inValue.dataReference = dataReference;
            inValue.dataXML = dataXML;
            inValue.paramXML = paramXML;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.FirmNr = FirmNr;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.CalculateDataObjectResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).CalculateDataObject(inValue);
            dataReference = retVal.dataReference;
            dataXML = retVal.dataXML;
            paramXML = retVal.paramXML;
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.CalculateDataObjectResponse> CalculateDataObjectAsync(IZOKALE_WEBSERVICE.WCFService.CalculateDataObjectRequest request) {
            return base.Channel.CalculateDataObjectAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.ExecQueryResponse IZOKALE_WEBSERVICE.WCFService.ISvc.ExecQuery(IZOKALE_WEBSERVICE.WCFService.ExecQueryRequest request) {
            return base.Channel.ExecQuery(request);
        }
        
        public void ExecQuery(string sqlText, string orderByText, string securityCode, ref object resultXML, ref string errorString, ref byte status, string LbsLoadPass) {
            IZOKALE_WEBSERVICE.WCFService.ExecQueryRequest inValue = new IZOKALE_WEBSERVICE.WCFService.ExecQueryRequest();
            inValue.sqlText = sqlText;
            inValue.orderByText = orderByText;
            inValue.securityCode = securityCode;
            inValue.resultXML = resultXML;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            IZOKALE_WEBSERVICE.WCFService.ExecQueryResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).ExecQuery(inValue);
            resultXML = retVal.resultXML;
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.ExecQueryResponse> ExecQueryAsync(IZOKALE_WEBSERVICE.WCFService.ExecQueryRequest request) {
            return base.Channel.ExecQueryAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.DirectQueryResponse IZOKALE_WEBSERVICE.WCFService.ISvc.DirectQuery(IZOKALE_WEBSERVICE.WCFService.DirectQueryRequest request) {
            return base.Channel.DirectQuery(request);
        }
        
        public void DirectQuery(string sqlText, string securityCode, ref string errorString, ref byte status, string LbsLoadPass) {
            IZOKALE_WEBSERVICE.WCFService.DirectQueryRequest inValue = new IZOKALE_WEBSERVICE.WCFService.DirectQueryRequest();
            inValue.sqlText = sqlText;
            inValue.securityCode = securityCode;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            IZOKALE_WEBSERVICE.WCFService.DirectQueryResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).DirectQuery(inValue);
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.DirectQueryResponse> DirectQueryAsync(IZOKALE_WEBSERVICE.WCFService.DirectQueryRequest request) {
            return base.Channel.DirectQueryAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.getValueResponse IZOKALE_WEBSERVICE.WCFService.ISvc.getValue(IZOKALE_WEBSERVICE.WCFService.getValueRequest request) {
            return base.Channel.getValue(request);
        }
        
        public void getValue(short Flag, ref int Value, bool isFlag, string securityCode, string LbsLoadPass) {
            IZOKALE_WEBSERVICE.WCFService.getValueRequest inValue = new IZOKALE_WEBSERVICE.WCFService.getValueRequest();
            inValue.Flag = Flag;
            inValue.Value = Value;
            inValue.isFlag = isFlag;
            inValue.securityCode = securityCode;
            inValue.LbsLoadPass = LbsLoadPass;
            IZOKALE_WEBSERVICE.WCFService.getValueResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).getValue(inValue);
            Value = retVal.Value;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.getValueResponse> getValueAsync(IZOKALE_WEBSERVICE.WCFService.getValueRequest request) {
            return base.Channel.getValueAsync(request);
        }
        
        public string getTableName(int TableNr) {
            return base.Channel.getTableName(TableNr);
        }
        
        public System.Threading.Tasks.Task<string> getTableNameAsync(int TableNr) {
            return base.Channel.getTableNameAsync(TableNr);
        }
        
        public void printDoc(short doctype, int docRef, string termCode, string designTitle, string printerCode, short printCnt, string securityCode, string LbsLoadPass) {
            base.Channel.printDoc(doctype, docRef, termCode, designTitle, printerCode, printCnt, securityCode, LbsLoadPass);
        }
        
        public System.Threading.Tasks.Task printDocAsync(short doctype, int docRef, string termCode, string designTitle, string printerCode, short printCnt, string securityCode, string LbsLoadPass) {
            return base.Channel.printDocAsync(doctype, docRef, termCode, designTitle, printerCode, printCnt, securityCode, LbsLoadPass);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.getInfoResponse IZOKALE_WEBSERVICE.WCFService.ISvc.getInfo(IZOKALE_WEBSERVICE.WCFService.getInfoRequest request) {
            return base.Channel.getInfo(request);
        }
        
        public void getInfo(ref object resultXML, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.getInfoRequest inValue = new IZOKALE_WEBSERVICE.WCFService.getInfoRequest();
            inValue.resultXML = resultXML;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.getInfoResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).getInfo(inValue);
            resultXML = retVal.resultXML;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.getInfoResponse> getInfoAsync(IZOKALE_WEBSERVICE.WCFService.getInfoRequest request) {
            return base.Channel.getInfoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.getStockPriceListResponse IZOKALE_WEBSERVICE.WCFService.ISvc.getStockPriceList(IZOKALE_WEBSERVICE.WCFService.getStockPriceListRequest request) {
            return base.Channel.getStockPriceList(request);
        }
        
        public void getStockPriceList(string priceParamJson, ref string priceListJson, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.getStockPriceListRequest inValue = new IZOKALE_WEBSERVICE.WCFService.getStockPriceListRequest();
            inValue.priceParamJson = priceParamJson;
            inValue.priceListJson = priceListJson;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.getStockPriceListResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).getStockPriceList(inValue);
            priceListJson = retVal.priceListJson;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.getStockPriceListResponse> getStockPriceListAsync(IZOKALE_WEBSERVICE.WCFService.getStockPriceListRequest request) {
            return base.Channel.getStockPriceListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.UsableCampaignCardsResponse IZOKALE_WEBSERVICE.WCFService.ISvc.UsableCampaignCards(IZOKALE_WEBSERVICE.WCFService.UsableCampaignCardsRequest request) {
            return base.Channel.UsableCampaignCards(request);
        }
        
        public void UsableCampaignCards(int dataType, ref int dataReference, ref string dataXML, ref string paramXML, ref string errorString, ref byte status, string LbsLoadPass, int FirmNr, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.UsableCampaignCardsRequest inValue = new IZOKALE_WEBSERVICE.WCFService.UsableCampaignCardsRequest();
            inValue.dataType = dataType;
            inValue.dataReference = dataReference;
            inValue.dataXML = dataXML;
            inValue.paramXML = paramXML;
            inValue.errorString = errorString;
            inValue.status = status;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.FirmNr = FirmNr;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.UsableCampaignCardsResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).UsableCampaignCards(inValue);
            dataReference = retVal.dataReference;
            dataXML = retVal.dataXML;
            paramXML = retVal.paramXML;
            errorString = retVal.errorString;
            status = retVal.status;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.UsableCampaignCardsResponse> UsableCampaignCardsAsync(IZOKALE_WEBSERVICE.WCFService.UsableCampaignCardsRequest request) {
            return base.Channel.UsableCampaignCardsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.SendRecvEInvoiceDocumentsResponse IZOKALE_WEBSERVICE.WCFService.ISvc.SendRecvEInvoiceDocuments(IZOKALE_WEBSERVICE.WCFService.SendRecvEInvoiceDocumentsRequest request) {
            return base.Channel.SendRecvEInvoiceDocuments(request);
        }
        
        public void SendRecvEInvoiceDocuments(int send, int recv, string refs, ref string msg, string LbsLoadPass, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.SendRecvEInvoiceDocumentsRequest inValue = new IZOKALE_WEBSERVICE.WCFService.SendRecvEInvoiceDocumentsRequest();
            inValue.send = send;
            inValue.recv = recv;
            inValue.refs = refs;
            inValue.msg = msg;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.SendRecvEInvoiceDocumentsResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).SendRecvEInvoiceDocuments(inValue);
            msg = retVal.msg;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.SendRecvEInvoiceDocumentsResponse> SendRecvEInvoiceDocumentsAsync(IZOKALE_WEBSERVICE.WCFService.SendRecvEInvoiceDocumentsRequest request) {
            return base.Channel.SendRecvEInvoiceDocumentsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.SendEArchiveDocumentsResponse IZOKALE_WEBSERVICE.WCFService.ISvc.SendEArchiveDocuments(IZOKALE_WEBSERVICE.WCFService.SendEArchiveDocumentsRequest request) {
            return base.Channel.SendEArchiveDocuments(request);
        }
        
        public void SendEArchiveDocuments(string refs, ref string msg, string LbsLoadPass, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.SendEArchiveDocumentsRequest inValue = new IZOKALE_WEBSERVICE.WCFService.SendEArchiveDocumentsRequest();
            inValue.refs = refs;
            inValue.msg = msg;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.SendEArchiveDocumentsResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).SendEArchiveDocuments(inValue);
            msg = retVal.msg;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.SendEArchiveDocumentsResponse> SendEArchiveDocumentsAsync(IZOKALE_WEBSERVICE.WCFService.SendEArchiveDocumentsRequest request) {
            return base.Channel.SendEArchiveDocumentsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.SendRecvEDispatchDocumentsResponse IZOKALE_WEBSERVICE.WCFService.ISvc.SendRecvEDispatchDocuments(IZOKALE_WEBSERVICE.WCFService.SendRecvEDispatchDocumentsRequest request) {
            return base.Channel.SendRecvEDispatchDocuments(request);
        }
        
        public void SendRecvEDispatchDocuments(int send, int recv, string dispatchRefs, string receiptRefs, ref string msg, string LbsLoadPass, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.SendRecvEDispatchDocumentsRequest inValue = new IZOKALE_WEBSERVICE.WCFService.SendRecvEDispatchDocumentsRequest();
            inValue.send = send;
            inValue.recv = recv;
            inValue.dispatchRefs = dispatchRefs;
            inValue.receiptRefs = receiptRefs;
            inValue.msg = msg;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.SendRecvEDispatchDocumentsResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).SendRecvEDispatchDocuments(inValue);
            msg = retVal.msg;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.SendRecvEDispatchDocumentsResponse> SendRecvEDispatchDocumentsAsync(IZOKALE_WEBSERVICE.WCFService.SendRecvEDispatchDocumentsRequest request) {
            return base.Channel.SendRecvEDispatchDocumentsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.SendESEVoucherDocumentsResponse IZOKALE_WEBSERVICE.WCFService.ISvc.SendESEVoucherDocuments(IZOKALE_WEBSERVICE.WCFService.SendESEVoucherDocumentsRequest request) {
            return base.Channel.SendESEVoucherDocuments(request);
        }
        
        public void SendESEVoucherDocuments(string clfRefs, string cashRefs, ref string msg, string LbsLoadPass, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.SendESEVoucherDocumentsRequest inValue = new IZOKALE_WEBSERVICE.WCFService.SendESEVoucherDocumentsRequest();
            inValue.clfRefs = clfRefs;
            inValue.cashRefs = cashRefs;
            inValue.msg = msg;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.SendESEVoucherDocumentsResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).SendESEVoucherDocuments(inValue);
            msg = retVal.msg;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.SendESEVoucherDocumentsResponse> SendESEVoucherDocumentsAsync(IZOKALE_WEBSERVICE.WCFService.SendESEVoucherDocumentsRequest request) {
            return base.Channel.SendESEVoucherDocumentsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.SendESEPreceiptDocumentsResponse IZOKALE_WEBSERVICE.WCFService.ISvc.SendESEPreceiptDocuments(IZOKALE_WEBSERVICE.WCFService.SendESEPreceiptDocumentsRequest request) {
            return base.Channel.SendESEPreceiptDocuments(request);
        }
        
        public void SendESEPreceiptDocuments(string refs, ref string msg, string LbsLoadPass, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.SendESEPreceiptDocumentsRequest inValue = new IZOKALE_WEBSERVICE.WCFService.SendESEPreceiptDocumentsRequest();
            inValue.refs = refs;
            inValue.msg = msg;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.SendESEPreceiptDocumentsResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).SendESEPreceiptDocuments(inValue);
            msg = retVal.msg;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.SendESEPreceiptDocumentsResponse> SendESEPreceiptDocumentsAsync(IZOKALE_WEBSERVICE.WCFService.SendESEPreceiptDocumentsRequest request) {
            return base.Channel.SendESEPreceiptDocumentsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.GetEDocumentContentResponse IZOKALE_WEBSERVICE.WCFService.ISvc.GetEDocumentContent(IZOKALE_WEBSERVICE.WCFService.GetEDocumentContentRequest request) {
            return base.Channel.GetEDocumentContent(request);
        }
        
        public void GetEDocumentContent(string docTyp, string outFormat, string GUID, ref string msg, string LbsLoadPass, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.GetEDocumentContentRequest inValue = new IZOKALE_WEBSERVICE.WCFService.GetEDocumentContentRequest();
            inValue.docTyp = docTyp;
            inValue.outFormat = outFormat;
            inValue.GUID = GUID;
            inValue.msg = msg;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.GetEDocumentContentResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).GetEDocumentContent(inValue);
            msg = retVal.msg;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.GetEDocumentContentResponse> GetEDocumentContentAsync(IZOKALE_WEBSERVICE.WCFService.GetEDocumentContentRequest request) {
            return base.Channel.GetEDocumentContentAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.UpdateEDocumentStatusResponse IZOKALE_WEBSERVICE.WCFService.ISvc.UpdateEDocumentStatus(IZOKALE_WEBSERVICE.WCFService.UpdateEDocumentStatusRequest request) {
            return base.Channel.UpdateEDocumentStatus(request);
        }
        
        public void UpdateEDocumentStatus(string docTyp, string refs, ref string msg, string LbsLoadPass, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.UpdateEDocumentStatusRequest inValue = new IZOKALE_WEBSERVICE.WCFService.UpdateEDocumentStatusRequest();
            inValue.docTyp = docTyp;
            inValue.refs = refs;
            inValue.msg = msg;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.UpdateEDocumentStatusResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).UpdateEDocumentStatus(inValue);
            msg = retVal.msg;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.UpdateEDocumentStatusResponse> UpdateEDocumentStatusAsync(IZOKALE_WEBSERVICE.WCFService.UpdateEDocumentStatusRequest request) {
            return base.Channel.UpdateEDocumentStatusAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IZOKALE_WEBSERVICE.WCFService.SaveEDocumentResponse IZOKALE_WEBSERVICE.WCFService.ISvc.SaveEDocument(IZOKALE_WEBSERVICE.WCFService.SaveEDocumentRequest request) {
            return base.Channel.SaveEDocument(request);
        }
        
        public void SaveEDocument(int approvalRef, ref string msg, string LbsLoadPass, string securityCode) {
            IZOKALE_WEBSERVICE.WCFService.SaveEDocumentRequest inValue = new IZOKALE_WEBSERVICE.WCFService.SaveEDocumentRequest();
            inValue.approvalRef = approvalRef;
            inValue.msg = msg;
            inValue.LbsLoadPass = LbsLoadPass;
            inValue.securityCode = securityCode;
            IZOKALE_WEBSERVICE.WCFService.SaveEDocumentResponse retVal = ((IZOKALE_WEBSERVICE.WCFService.ISvc)(this)).SaveEDocument(inValue);
            msg = retVal.msg;
        }
        
        public System.Threading.Tasks.Task<IZOKALE_WEBSERVICE.WCFService.SaveEDocumentResponse> SaveEDocumentAsync(IZOKALE_WEBSERVICE.WCFService.SaveEDocumentRequest request) {
            return base.Channel.SaveEDocumentAsync(request);
        }
    }
}
